export { AddressContollerService } from './services/address-contoller.service';
export { CompanyService } from './services/company.service';
export { CriterionService } from './services/criterion.service';
export { CriterionOfferService } from './services/criterion-offer.service';
export { CriterionStudentService } from './services/criterion-student.service';
export { EvaluationService } from './services/evaluation.service';
export { OfferService } from './services/offer.service';
export { SectionService } from './services/section.service';
export { StudentService } from './services/student.service';
